### ISSUE TITLE
Grade do 1° meetup NUG-CE

### ISSUE THREAD

**Issue by mabrasil** [nug-ce/nug-ce#1]
Pessoal, precisamos fechar a grade do nosso *1° meetup* - até por questões de divulgação mesmo. Gostaria que comentassem aqui algumas informações no seguinte formato:

>**Nome**: Ciço
**Ordem da Talk**: 1° 
**Descrição Pessoal**: Não frequentador de eventos.
**Título Palestra**: Título massa
**Descrição da Palestra**: Algum CMS que roda no node e eu nunca lembro o nome.
**Estimativa de Tempo**:
cc @AbraaoAlves, @cicerohen, @cjpatoilo, @felipesousa

**Comment by cicerohen** [comment]
>**Nome**: Cícero Viana
**Ordem da Talk**: 2° 
**Descrição Pessoal**: Desenvolvedor web entusiasta MEAN e Ionic Framework
**Título Palestra**: KeystoneJS, Uma Alternativa Simples e Prática. 
**Descrição da Palestra**:  Introdução ao mais novo(e talvez melhor) CMS Node.js do momento

**Comment by cjpatoilo** [comment]
Nome: CJ Patoilo
Ordem da Talk: 1° 
Descrição Pessoal: Obcecado por performance com foco no desenvolvimento ágil e escalável,  e perfeccionista com codificação legível, semântica e reutilizável. Co-fundador do DEV IO onde compartilha conhecimentos e experiências. Criador da Hope: app que incentivará a doação de sangue informando os locais mais próximos para doação. Tudo feito com amor e tecnologias baseadas em JavaScript.
Título Palestra: Meteor e o Princípio da Programação Reativa
Descrição da Palestra: Crie aplicativos web que são uma delícia de usar, mais rápido do que você jamais imaginou ser possível. 
Estimativa de Tempo: ~40min

**Comment by felipesousa** [comment]
> Nome: Felipe Sousa
> Ordem da Talk: 4ª
> Título da Palestra: Static Generators - Experimente inovar.
> Descrição da palestra: Entenda como funciona e começe a criar suas páginas estáticas.
> Descrição Pessoal: Desenvolvedor Front-end, entusiasta JavaScript e fascinado por projetos Open Source. 
> Estimativa de tempo: ~20min

**Comment by AbraaoAlves** [comment]
> Nome: Abraão Alves
Ordem da Talk: 3° 
Descrição Pessoal: Desenvolvedor de pessoas e softwares, empreendedor, palestrante nas horas vagas e membro do time oficial de tênis de mesa do IFCE.
Título Palestra: Debug Is On The Table. 
Descrição da Palestra: Todo desenvolvedor deve saber como o código é executado, mas nem sempre essa tarefa é fácil sem um debug. Conheça e compare as várias opções disponíveis para "debugar" seu aplicativo em Node.js.
Estimativa de Tempo: ~25min

**Comment by mabrasil** [comment]
**Nome**: Matheus Brasil
**Ordem da Talk**: 5°
**Descrição Pessoal**: Defensor da filosofia UNIX, alquimista da web e sommelier de linguagens de programação. No tempo livre, estuda Informática no IFCE, além de escutar muito rock e indie.
**Título Palestra**: Repensando automação: NPM to rule them all
**Descrição da Palestra**: Algumas coisas no mundo JavaScript podem demandar um número considerável de tarefas: gerenciamento de assets, compilação e minificação  de estilos, concatenação, minificação e compressão de arquivos Javascript  etc. Temos muitas ferramentas incríveis pra nos ajudar nesses processos: Grunt e Gulp são as que mais caíram nas graças da galera - mas será que elas realmente são necessárias?
**Estimativa de Tempo**: ~25min

**Comment by mabrasil** [comment]
That's it, galero :smile_cat:
